@extends('layouts.main')

@section('container')
    <h1 class="text-center my-5">Visi dan Misi</h1>
    <div class="container">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque necessitatibus sint nihil placeat perferendis quasi possimus at maiores, aspernatur non dolorum neque sapiente maxime nemo quidem dolore omnis id assumenda sunt quae odio accusamus fugiat a. Sapiente ab sunt repudiandae, error, corporis recusandae numquam veniam voluptates quisquam consequuntur soluta repellendus!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa odio quam reprehenderit a perferendis sed ducimus vitae vero, esse commodi in nobis quasi consequuntur expedita animi magni nemo nostrum, minus minima maiores possimus tempora iure illo eveniet? Totam atque suscipit nobis illo tempore ab aliquid necessitatibus iure at expedita aliquam dignissimos sunt omnis earum soluta, harum adipisci consectetur quia cumque repudiandae repellat dolore ipsam. Error, magnam ab! Eligendi fuga doloremque fugit, eos dolore molestias quia incidunt quibusdam, voluptate et amet commodi obcaecati illum facilis animi doloribus cupiditate quasi suscipit porro! Ipsa eum minus omnis dicta numquam mollitia consectetur ratione recusandae cupiditate error magnam porro quos, ducimus qui earum, cumque ipsam voluptates ab, voluptatem animi blanditiis! Ex incidunt porro distinctio, dolore minima officia? Facilis accusamus sint id totam possimus, voluptatibus aperiam, quidem, nam impedit consequatur minus quas vero ab voluptate repellat eligendi eaque quam cupiditate doloribus placeat obcaecati excepturi odio error?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Culpa voluptas delectus illo, veritatis praesentium ab voluptatibus corrupti dicta placeat architecto iste eveniet fugiat, excepturi eligendi ducimus ut qui temporibus mollitia atque id, officia ratione! Veritatis itaque perferendis impedit ducimus autem quia illo blanditiis suscipit reiciendis laudantium iste eveniet odio at natus vel nobis dicta error, ex hic? Minus aliquid quo deserunt dolor doloremque iste nisi dolorem? Sunt enim mollitia in nostrum tempore nisi ab delectus? Necessitatibus reiciendis iste fugit, at nobis eum voluptatum cum architecto odio commodi sequi eveniet illo recusandae aliquid tempore nulla consectetur laborum sed, neque ex quo!</p>
    </div>
@endsection